steps:
  # Build container1-service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/file-service:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/file-service:latest',
      './container1-service'
    ]

  # Build container2-service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/calc-service:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/calc-service:latest',
      './container2-service'
    ]

  # Push both images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/file-service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/file-service:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/calc-service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/calc-service:latest']

  # Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - k8s/  # Ensure the 'k8s' directory contains deployment and service YAML files
    timeout: "600s"  # Set a 10-minute timeout for deployment

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/file-service:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/file-service:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/calc-service:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/k8s-assignment-repo/calc-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY

