stages:
  - init
  - plan
  - apply

terraform_init:
  stage: init
  script:
    - terraform init
  tags:
    - docker
  only:
    - terraform
  when: manual

terraform_plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  dependencies:
    - terraform_init
  only:
    - terraform

terraform_apply:
  stage: apply
  script:
    - terraform apply -input=false tfplan
  dependencies:
    - terraform_plan
  environment:
    name: gke_infrastructure
  only:
    - terraform
  when: manual

