apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-service
  labels:
    app: calc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc-service
  template:
    metadata:
      labels:
        app: calc-service
    spec:
      containers:
        - name: calc-service
          image: us-central1-docker.pkg.dev/k8s-assignment-csci5409/k8s-assignment-repo/calc-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: STORAGE_DIR
              value: "/Kenee_Ashok_PV_dir"
          volumeMounts:
            - name: data-volume
              mountPath: /Kenee_Ashok_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: k8s-assignment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: calc-service
