apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: us-central1-docker.pkg.dev/k8s-assignment-csci5409/k8s-assignment-repo/file-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: CONTAINER2_URL
              value: "http://calc-service:3001"
            - name: STORAGE_DIR
              value: "/Kenee_Ashok_PV_dir"
          readinessProbe:
            httpGet:
              port: 3001
              path: /health
            initialDelaySeconds: 300
            periodSeconds: 30
          livenessProbe:
            httpGet:
              port: 3001
              path: /health
            initialDelaySeconds: 300
            periodSeconds: 10
          volumeMounts:
            - name: data-volume
              mountPath: /Kenee_Ashok_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: k8s-assignment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: file-service
