apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-assignment-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: k8s-assignment-pd
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-assignment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
